# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: InterfaceFluidics.Autobench.Release-Candidate
PackageVersion: 0.92.2.0
PackageLocale: en-US
Publisher: Interface Fluidics
PackageName: Autobench Release-Candidate
License: Proprietary
ShortDescription: Autobench
ManifestType: defaultLocale
ManifestVersion: 1.9.0
