# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: InterfaceFluidics.Autoanalysis.Release-Candidate
PackageVersion: 1.12.14.0
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msix
PackageFamilyName: Autoanalysis-Release-Candidate_adgv3mcaarp50
Installers:
- Architecture: neutral
  InstallerUrl: https://apps.interfacefluidics.com/autoanalysis/release-candidate/1.12.14.0/autoanalysis-1.12.14.0.msix
  InstallerSha256: CE64B2127CBC8A2BC2D38BB8CB0706A1B79739F872605CF9C6DED241A1AB253B
  SignatureSha256: 94AE940FBDD1F277DEDF9E9A9ABE827FA15EFCF8CA6561990C4A1942EACAEE46
ManifestType: installer
ManifestVersion: 1.9.0
